name: fat--tracker
version: 0.1.0
description: >-
  Cross-platform nutrition, workout, and inventory management app with Firebase sync and Google Calendar integration.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0 # For Google Calendar API
  provider: ^6.0.0
  hive: ^2.2.3 # Latest stable as of April 2025
  hive_flutter: ^1.1.0 # Latest stable as of April 2025
  path_provider: ^2.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
